name: Popcorn
slug: extaas_popcorn
version: "3.1.1.2"
description: Osaühing X product for local movie discovery, personal and family watchlists, reminders, notifications and movie-night controls in Home Assistant.
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true
startup: "application"
boot: auto
init: false
ingress: true
ingress_port: 8080
host_network: true
panel_icon: mdi:television-classic
panel_title: Popcorn
options:
  themoviedb_api: "123"
#  api_url: "http://example.com"
#  refresh_interval: 10
schema:
  themoviedb_api: str
#  api_url: str
#  refresh_interval: int
