name: Addon Template
description: Simple sample code to get you started
version: 0.0.1
slug: addon_template
init: false
arch:
- amd64
- armv7
- armhf
- aarch64
- i386
panel_icon: "mdi:home-assistant"
panel_title: My Template
ingress: true
ingress_port: 8099
startup: "application"
boot: auto

