<script>
  import { onMount } from 'svelte';
  let cameras = [], draft = null, message = '', showPassword = false;
  let preview = '', previewBusy = false, previewError = '';
  let activeCamera = '', detailPreview = { hq:'', lq:'' }, detailBusy = '';
  let generalSettings={discoveryPort:3702,onvifPort:8091,autoDiscovery:true,fragmentMs:100,gop:5,buffering:false},settingsOpen=false;
  let detected=[],scanning=false,scanNetwork='';
  let dismissedDetected=new Set();
  const endpointKey = camera => `${camera.host}:${camera.port}`;
  function configuredEndpoint(camera){return cameras.some(item=>{try{const url=new URL(item.hq);return url.hostname===camera.host&&Number(url.port||554)===Number(camera.port)}catch{return false}})}
  $: visibleDetected=detected.filter(camera=>!dismissedDetected.has(endpointKey(camera))&&!configuredEndpoint(camera));
  const loadingPoster='/loading.gif';
  const blank = () => ({ name:'', model:'RTSP Bridge', ipMode:'dhcp', virtualIp:'', username:'onvif', password:'', hq:'', lq:'', width:1920, height:1080, fps:25 });
  async function api(options={}) { const response=await fetch('/api/cameras',{headers:{'content-type':'application/json'},...options}); const data=await response.json(); if(!response.ok) throw Error(data.error); return data; }
  async function load(){ const [cameraData,settingData]=await Promise.all([api(),fetch('/api/settings').then(response=>response.json())]);cameras=cameraData.cameras;generalSettings=settingData; }
  async function saveGeneralSettings(){const response=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(generalSettings)});if(!response.ok)throw Error((await response.json()).error);generalSettings=await response.json();settingsOpen=false;message='Application settings saved.';setTimeout(()=>message='',10000)}
  async function scanCameras(){scanning=true;detected=[];dismissedDetected=new Set();try{const response=await fetch('/api/discover',{method:'POST'}),data=await response.json();if(!response.ok)throw Error(data.error);detected=data.cameras;scanNetwork=data.network;message=`Found ${detected.length} possible RTSP camera${detected.length===1?'':'s'} on ${scanNetwork}.`;setTimeout(()=>message='',10000)}catch(error){message=error.message}finally{scanning=false}}
  function useDetected(camera){draft={...blank(),name:`Camera ${camera.host}`,hq:camera.url};showPassword=false}
  async function save(){ await api({method:draft.id?'PUT':'POST',body:JSON.stringify(draft)}); draft=null; message='Camera saved and ready for ONVIF discovery.'; setTimeout(()=>message='',10000); await load(); }
  async function remove(camera){ if(confirm(`Delete ${camera.name}?`)){ await api({method:'DELETE',body:JSON.stringify({id:camera.id})}); await load(); } }
  function openPreview(camera){preview=`/api/stream?id=${encodeURIComponent(camera.id)}&t=${Date.now()}`;previewError=''}
  function beginPreview(camera,event){activeCamera=camera.id;event.currentTarget.querySelector('video')?.play().catch(()=>{})}
  function endPreview(event){activeCamera='';event.currentTarget.querySelector('video')?.pause()}
  onMount(()=>{const style=document.createElement('style');style.textContent='.check{display:flex!important;flex-wrap:wrap;align-items:center}.check>small{flex:0 0 100%;padding-left:27px}.grouped>.full-span{display:grid!important;grid-column:1/-1!important}.grouped>h3:nth-of-type(2)+label{grid-column:auto!important}';document.head.append(style);return()=>style.remove()});
  async function previewStream(kind){const stream=draft?.[kind];if(!stream)return;detailBusy=kind;previewError='';try{const response=await fetch('/api/stream',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stream})}),data=await response.json();if(!response.ok)throw Error(data.error);const labels=[...document.querySelectorAll('.stream-field')],label=labels.find(item=>item.textContent.includes(kind==='lq'?'LQ RTSP':'HQ RTSP')),details=label?.querySelector('details');details?.querySelector('.stream-video')?.remove();if(details){const video=document.createElement('video');video.className='stream-video';video.src=data.url;video.autoplay=true;video.muted=true;video.playsInline=true;video.style.width='-webkit-fill-available';details.append(video)}}catch(error){previewError=error.message}finally{detailBusy=''}}
  onMount(()=>{load();const addLoading=()=>document.querySelectorAll('video').forEach(video=>{video.removeAttribute('poster');video.style.background=`#080d13 url('${loadingPoster}') center / 30px 30px no-repeat`}),observer=new MutationObserver(addLoading);observer.observe(document.body,{childList:true,subtree:true});addLoading();const autoLoad=(event)=>{const details=event.target.closest?.('details');if(!details)return;setTimeout(()=>{if(details.open)previewStream(details.closest('label')?.textContent?.includes('LQ RTSP')?'lq':'hq')})};document.addEventListener('toggle',autoLoad,true);return()=>{observer.disconnect();document.removeEventListener('toggle',autoLoad,true)}});
</script>

<svelte:head><title>RTSP to ONVIF</title><style>.list>article{grid-template-columns:min-content 1fr auto!important}h2,h3{margin:0}.grid label:nth-child(7),.onvif-user,.check{grid-column:auto!important}.check{display:flex!important;align-items:center}.check input{width:auto}.grouped>label:nth-of-type(3){display:none}.grouped hr,.grouped h3,.grouped .stream-field,.grouped .three{grid-column:1/-1;width:-webkit-fill-available}.grouped hr{border-width:1px 0 0;opacity:.5}.backdrop form>p:last-of-type{margin-top:2em}.stream-field details,.preview{overflow:auto}.stream-field details>button,.stream-field details>img{display:none}.stream-field video{width:-webkit-fill-available}@media(max-width:650px){.list>article{grid-template-columns:min-content 1fr!important}}</style></svelte:head>
<header><div><span>X APPLICATION</span><h1>RTSP to ONVIF</h1><p>Expose the original RTSP stream through ONVIF without adding delay to the recorder path.</p></div><div class="actions"><button disabled={scanning} on:click={scanCameras}>{scanning?'Scanning network…':'Find RTSP cameras'}</button><button on:click={()=>settingsOpen=true}>Settings</button><button class="primary" on:click={()=>{draft=blank();showPassword=false}}>Add camera</button></div></header>
<main>
  {#if message}<p class="notice">{message}</p>{/if}
  <section class="summary"><article><small>CAMERAS</small><b>{cameras.length}</b></article><article><small>DISCOVERY</small><b>WS-Discovery :3702</b></article><article><small>MODE</small><b>RTSP passthrough</b></article></section>
  {#if visibleDetected.length}<details class="list detected" style="margin-bottom:24px" open><summary>Detected RTSP endpoints ({visibleDetected.length})</summary><p>Open RTSP ports found on {scanNetwork}. Confirm the stream path and credentials.</p>{#each visibleDetected as camera}<article><div><h3>{camera.host}:{camera.port}</h3><code>{camera.url}</code></div><div class="actions"><button on:click={()=>useDetected(camera)}>Configure</button><button on:click={()=>dismissedDetected=new Set([...dismissedDetected,endpointKey(camera)])} aria-label={`Hide ${camera.host}:${camera.port}`}>×</button></div></article>{/each}</details>{/if}
  <section class="list"><div class="head"><h2>Virtual cameras</h2><p>Available to ONVIF-compatible recorders and automation platforms.</p></div>
    {#each cameras as camera}<article on:mouseenter={(event)=>beginPreview(camera,event)} on:mouseleave={endPreview}><button class="camera-view" style="width:160px;height:90px;padding:0;overflow:hidden;background:#080d13" on:click={()=>openPreview(camera)} aria-label={`Open ${camera.name} preview`}><video muted playsinline preload="none" style:filter={activeCamera===camera.id?'none':'blur(3px)'} style="width:100%;height:100%;display:block;object-fit:cover;transition:filter .2s" src={`/api/stream?id=${encodeURIComponent(camera.id)}`}></video></button><div><h3>{camera.name}</h3><p>{camera.model} · {camera.width}×{camera.height} · {camera.fps} FPS</p><code>{camera.hq}</code>{#if camera.lq}<small>LQ configured</small>{/if}</div><div class="actions"><button on:click={()=>{draft={...camera};showPassword=false;detailPreview={hq:'',lq:''}}}>Edit</button><button class="danger" on:click={()=>remove(camera)}>Delete</button></div></article>
    {:else}<div class="empty"><b>No virtual cameras yet</b><span>Add an RTSP stream to expose it through ONVIF.</span></div>{/each}
  </section>
</main>
{#if settingsOpen}<div class="backdrop"><form on:submit|preventDefault={saveGeneralSettings}><header><div><span>APPLICATION</span><h2>RTSP to ONVIF settings</h2></div><button type="button" on:click={()=>settingsOpen=false}>×</button></header><p>The recorder receives the original RTSP URL directly. The MP4, GOP and buffering settings below affect browser previews only.</p><div class="grid"><label>WS-Discovery port<input type="number" min="1" max="65535" bind:value={generalSettings.discoveryPort}><small>UDP port used by systems searching for ONVIF cameras. Recommended: 3702.</small></label><label>ONVIF port<input type="number" min="1024" max="65535" bind:value={generalSettings.onvifPort}><small>HTTP port serving ONVIF device and media services. Must be free on the host.</small></label><label>MP4 fragment (ms)<input type="number" min="50" max="2000" bind:value={generalSettings.fragmentMs}><small>Smaller fragments start browser preview sooner. Recommended low latency: 50–100 ms.</small></label><label>GOP frames<input type="number" min="1" max="300" bind:value={generalSettings.gop}><small>Distance between preview keyframes. Recommended low latency: 1–5.</small></label><label>Preview buffering<select bind:value={generalSettings.buffering}><option value={false}>Disabled — lowest delay</option><option value={true}>Enabled — more stable</option></select><small>Enable only if the preview stutters or the RTSP network is unreliable.</small></label><label class="check"><input type="checkbox" bind:checked={generalSettings.autoDiscovery}> Auto-discovery (WS-Discovery)<small>Advertise configured cameras automatically on the local network.</small></label></div><p><b>Lowest-delay preview:</b> 50 ms fragments, GOP 1–5 and buffering disabled. The camera encoder's own GOP and the browser can still add latency.</p><button class="primary wide">Save settings</button></form></div>{/if}
{#if draft}<div class="backdrop" on:click={event=>event.currentTarget===event.target&&(draft=null)}><form on:submit|preventDefault={save}><header><div><span>CAMERA</span><h2>{draft.id?'Edit camera':'Add camera'}</h2></div><button type="button" on:click={()=>draft=null}>×</button></header><div class="grid grouped"><h3>Device information</h3><label>Name<input bind:value={draft.name} required placeholder="Front door"></label><label>Model<input bind:value={draft.model}></label><label>IP assignment<select bind:value={draft.ipMode}><option value="dhcp">DHCP — automatic</option><option value="static">Static — manual</option></select><small>DHCP is the default. The camera uses a stable generated MAC address, so a router reservation can be added later.</small></label>{#if draft.ipMode==='static'}<label>Static IP<input bind:value={draft.virtualIp} required inputmode="decimal" placeholder="10.0.0.201"><small>Use a free, reserved LAN address outside the DHCP pool.</small></label>{/if}<hr><h3>ONVIF account</h3><label>ONVIF username<input bind:value={draft.username} required></label><label>ONVIF password<div class="password-field"><input bind:value={draft.password} type={showPassword?'text':'password'} required><button type="button" on:click={()=>showPassword=!showPassword}>{showPassword?'Hide':'View'}</button></div></label><hr><h3>Preview</h3><label class="stream-field">HQ RTSP URL<input bind:value={draft.hq} type="url" required placeholder="rtsp://user:pass@camera/high"><details><summary>Preview HQ stream</summary></details></label><label class="stream-field">LQ RTSP URL <small>Optional</small><input bind:value={draft.lq} type="url" placeholder="rtsp://camera/low"><details><summary>Preview LQ stream</summary></details></label></div>{#if previewError}<p class="preview-error">{previewError}</p>{/if}<button class="primary wide">Save camera</button></form></div>{/if}
{#if previewBusy || preview || previewError}<div class="backdrop preview-backdrop" on:click={event=>event.currentTarget===event.target&&(preview='',previewError='')}><section class="preview"><header><h2>Camera preview</h2><button on:click={()=>{preview='';previewError=''}}>×</button></header>{#if previewBusy}<p>Connecting to RTSP stream…</p>{:else if previewError}<p class="preview-error">{previewError}</p>{:else}<video src={preview} autoplay muted playsinline style="width:-webkit-fill-available" aria-label="RTSP camera preview"></video>{/if}<button on:click={()=>{preview='';previewError=''}}>Close</button></section></div>{/if}

<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#080c11;color:#eaf0f5;font:14px Inter,system-ui,sans-serif}header,main{width:min(1100px,calc(100% - 32px));margin:auto}body>header,header{display:flex;align-items:end;justify-content:space-between;gap:20px;padding:48px 0 28px}span,small{color:#8996a4}header span,.summary small{color:#da3;font-size:10px;font-weight:800;letter-spacing:.16em}h1{font-size:42px;margin:5px 0}h2,h3,p{margin-top:0}header p,.head p{color:#8e9aa7}.primary{border:0;background:#da3;color:#181405;font-weight:800}.primary,button,input{border-radius:8px;padding:10px 13px}button{cursor:pointer;border:1px solid #34404c;background:#18202a;color:white}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:24px}.summary article{display:grid;gap:8px;padding:17px;background:#10161e;border:1px solid #26313d;border-radius:10px}.summary b{font-size:18px}.list{padding:20px;background:#0d131a;border:1px solid #26313d;border-radius:13px}.head{display:flex;justify-content:space-between}.list>article{display:grid;grid-template-columns:48px 1fr auto;align-items:center;gap:15px;padding:15px 0;border-top:1px solid #222d38}.camera-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:12px;background:#2b2510;color:#da3;font-size:25px}.list h3{margin:0 0 5px}.list article p{margin:0 0 5px;color:#8e9aa7}.list code{display:block;max-width:600px;overflow:hidden;text-overflow:ellipsis;color:#b8c2cc}.actions{display:flex;gap:6px;flex-wrap:wrap}.danger{color:#ff9ba5;border-color:#67333a}.empty{min-height:220px;display:grid;place-content:center;text-align:center;gap:8px;color:#8d99a6}.notice{padding:11px;border:1px solid #66581b;color:#da3;border-radius:8px}.backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:#000c;overflow:auto}.backdrop form,.preview{width:min(680px,100%);padding:22px;background:#10161e;border:1px solid #34404c;border-radius:14px}.backdrop form>header,.preview>header{width:100%;padding:0 0 18px}.backdrop h2{margin:4px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid label{display:grid;gap:6px;color:#aeb8c2}.grid label:nth-child(6),.grid label:nth-child(7),.three{grid-column:1/-1}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}input{width:100%;border:1px solid #34404c;background:#080d13;color:white}.password-field{display:flex;gap:6px}.password-field input{min-width:0}.password-field button{white-space:nowrap}.wide{width:100%;margin-top:16px}.preview{width:min(900px,100%)}.preview img{display:block;width:100%;max-height:70vh;object-fit:contain;margin-bottom:14px;border-radius:8px;background:#05080c}.preview-error{color:#ff9ba5}@media(max-width:650px){header,.head{align-items:stretch;flex-direction:column}.summary,.grid{grid-template-columns:1fr}.grid>*{grid-column:auto!important}.list>article{grid-template-columns:42px 1fr}.actions{grid-column:1/-1}.three{grid-template-columns:1fr}}</style>
