<script>
  import { onMount } from 'svelte';
  let cameras = [], draft = null, message = '', showPassword = false;
  let preview = '', previewBusy = false, previewError = '';
  let activeCamera = '', detailPreview = { hq:'', lq:'' }, detailBusy = '';
  const blank = () => ({ name:'', username:'onvif', password:'', manufacturer:'X Platform', model:'RTSP Bridge', hq:'', lq:'', width:1920, height:1080, fps:25 });
  async function api(options={}) { const response=await fetch('/api/cameras',{headers:{'content-type':'application/json'},...options}); const data=await response.json(); if(!response.ok) throw Error(data.error); return data; }
  async function load(){ cameras=(await api()).cameras; }
  async function save(){ await api({method:draft.id?'PUT':'POST',body:JSON.stringify(draft)}); draft=null; message='Camera saved and ready for ONVIF discovery.'; setTimeout(()=>message='',10000); await load(); }
  async function remove(camera){ if(confirm(`Delete ${camera.name}?`)){ await api({method:'DELETE',body:JSON.stringify({id:camera.id})}); await load(); } }
  function openPreview(camera){preview=`/api/stream?id=${encodeURIComponent(camera.id)}&t=${Date.now()}`;previewError=''}
  function beginPreview(camera,event){activeCamera=camera.id;event.currentTarget.querySelector('video')?.play().catch(()=>{})}
  function endPreview(event){activeCamera='';event.currentTarget.querySelector('video')?.pause()}
  async function previewStream(kind){const stream=draft?.[kind];if(!stream)return;detailBusy=kind;previewError='';try{const response=await fetch('/api/stream',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stream})}),data=await response.json();if(!response.ok)throw Error(data.error);const labels=[...document.querySelectorAll('.stream-field')],label=labels.find(item=>item.textContent.includes(kind==='lq'?'LQ RTSP':'HQ RTSP')),details=label?.querySelector('details');details?.querySelector('.stream-video')?.remove();if(details){const video=document.createElement('video');video.className='stream-video';video.src=data.url;video.controls=true;video.autoplay=true;video.muted=true;video.playsInline=true;video.style.width='-webkit-fill-available';details.append(video)}}catch(error){previewError=error.message}finally{detailBusy=''}}
  onMount(()=>{load();const autoLoad=(event)=>{const details=event.target.closest?.('details');if(!details)return;setTimeout(()=>{if(details.open)previewStream(details.closest('label')?.textContent?.includes('LQ RTSP')?'lq':'hq')})};document.addEventListener('toggle',autoLoad,true);return()=>document.removeEventListener('toggle',autoLoad,true)});
</script>

<svelte:head><title>RTSP to ONVIF</title><style>.list>article{grid-template-columns:min-content 1fr auto!important}.stream-field details{overflow:auto}.stream-field details>button,.stream-field details>img{display:none}.stream-field video{width:-webkit-fill-available}@media(max-width:650px){.list>article{grid-template-columns:min-content 1fr!important}}</style></svelte:head>
<header><div><span>X APPLICATION</span><h1>RTSP to ONVIF</h1><p>Present existing RTSP streams as virtual ONVIF cameras.</p></div><button class="primary" on:click={()=>{draft=blank();showPassword=false}}>Add camera</button></header>
<main>
  {#if message}<p class="notice">{message}</p>{/if}
  <section class="summary"><article><small>CAMERAS</small><b>{cameras.length}</b></article><article><small>DISCOVERY</small><b>WS-Discovery :3702</b></article><article><small>MODE</small><b>RTSP passthrough</b></article></section>
  <section class="list"><div class="head"><h2>Virtual cameras</h2><p>Available to ONVIF-compatible recorders and automation platforms.</p></div>
    {#each cameras as camera}<article on:mouseenter={(event)=>beginPreview(camera,event)} on:mouseleave={endPreview}><button class="camera-view" style="width:160px;height:90px;padding:0;overflow:hidden;background:#080d13" on:click={()=>openPreview(camera)} aria-label={`Open ${camera.name} preview`}><video muted playsinline preload="none" style:filter={activeCamera===camera.id?'none':'blur(3px)'} style="width:100%;height:100%;display:block;object-fit:cover;transition:filter .2s" src={`/api/stream?id=${encodeURIComponent(camera.id)}`}></video></button><div><h3>{camera.name}</h3><p>{camera.model} · {camera.width}×{camera.height} · {camera.fps} FPS</p><code>{camera.hq}</code>{#if camera.lq}<small>LQ configured</small>{/if}</div><div class="actions"><button on:click={()=>{draft={...camera};showPassword=false;detailPreview={hq:'',lq:''}}}>Edit</button><button class="danger" on:click={()=>remove(camera)}>Delete</button></div></article>
    {:else}<div class="empty"><b>No virtual cameras yet</b><span>Add an RTSP stream to expose it through ONVIF.</span></div>{/each}
  </section>
</main>
{#if draft}<div class="backdrop" on:click={event=>event.currentTarget===event.target&&(draft=null)}><form on:submit|preventDefault={save}><header><div><span>CAMERA</span><h2>{draft.id?'Edit camera':'Add camera'}</h2></div><button type="button" on:click={()=>draft=null}>×</button></header><div class="grid"><label>Name<input bind:value={draft.name} required placeholder="Front door"></label><label>ONVIF username<input bind:value={draft.username} required></label><label>ONVIF password<div class="password-field"><input bind:value={draft.password} type={showPassword?'text':'password'} required><button type="button" on:click={()=>showPassword=!showPassword}>{showPassword?'Hide':'View'}</button></div></label><label>Manufacturer<input bind:value={draft.manufacturer}></label><label>Model<input bind:value={draft.model}></label><label class="stream-field">HQ RTSP URL<input bind:value={draft.hq} type="url" required placeholder="rtsp://user:pass@camera/high"><details><summary>Preview HQ stream</summary><button type="button" disabled={!draft.hq||detailBusy==='hq'} on:click={()=>previewStream('hq')}>{detailBusy==='hq'?'Connecting…':'Load preview'}</button>{#if detailPreview.hq}<img src={detailPreview.hq} alt="HQ stream preview"/>{/if}</details></label><label class="stream-field">LQ RTSP URL <small>Optional</small><input bind:value={draft.lq} type="url" placeholder="rtsp://camera/low"><details><summary>Preview LQ stream</summary><button type="button" disabled={!draft.lq||detailBusy==='lq'} on:click={()=>previewStream('lq')}>{detailBusy==='lq'?'Connecting…':'Load preview'}</button>{#if detailPreview.lq}<img src={detailPreview.lq} alt="LQ stream preview"/>{/if}</details></label><div class="three"><label>Width<input bind:value={draft.width} type="number" min="320"></label><label>Height<input bind:value={draft.height} type="number" min="240"></label><label>FPS<input bind:value={draft.fps} type="number" min="1" max="60"></label></div></div>{#if previewError}<p class="preview-error">{previewError}</p>{/if}<button class="primary wide">Save camera</button></form></div>{/if}
{#if previewBusy || preview || previewError}<div class="backdrop preview-backdrop" on:click={event=>event.currentTarget===event.target&&(preview='',previewError='')}><section class="preview"><header><h2>Camera preview</h2><button on:click={()=>{preview='';previewError=''}}>×</button></header>{#if previewBusy}<p>Connecting to RTSP stream…</p>{:else if previewError}<p class="preview-error">{previewError}</p>{:else}<video src={preview} autoplay muted controls playsinline style="width:-webkit-fill-available" aria-label="RTSP camera preview"></video>{/if}<button on:click={()=>{preview='';previewError=''}}>Close</button></section></div>{/if}

<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#080c11;color:#eaf0f5;font:14px Inter,system-ui,sans-serif}header,main{width:min(1100px,calc(100% - 32px));margin:auto}body>header,header{display:flex;align-items:end;justify-content:space-between;gap:20px;padding:48px 0 28px}span,small{color:#8996a4}header span,.summary small{color:#da3;font-size:10px;font-weight:800;letter-spacing:.16em}h1{font-size:42px;margin:5px 0}h2,h3,p{margin-top:0}header p,.head p{color:#8e9aa7}.primary{border:0;background:#da3;color:#181405;font-weight:800}.primary,button,input{border-radius:8px;padding:10px 13px}button{cursor:pointer;border:1px solid #34404c;background:#18202a;color:white}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:24px}.summary article{display:grid;gap:8px;padding:17px;background:#10161e;border:1px solid #26313d;border-radius:10px}.summary b{font-size:18px}.list{padding:20px;background:#0d131a;border:1px solid #26313d;border-radius:13px}.head{display:flex;justify-content:space-between}.list>article{display:grid;grid-template-columns:48px 1fr auto;align-items:center;gap:15px;padding:15px 0;border-top:1px solid #222d38}.camera-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:12px;background:#2b2510;color:#da3;font-size:25px}.list h3{margin:0 0 5px}.list article p{margin:0 0 5px;color:#8e9aa7}.list code{display:block;max-width:600px;overflow:hidden;text-overflow:ellipsis;color:#b8c2cc}.actions{display:flex;gap:6px;flex-wrap:wrap}.danger{color:#ff9ba5;border-color:#67333a}.empty{min-height:220px;display:grid;place-content:center;text-align:center;gap:8px;color:#8d99a6}.notice{padding:11px;border:1px solid #66581b;color:#da3;border-radius:8px}.backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:#000c;overflow:auto}.backdrop form,.preview{width:min(680px,100%);padding:22px;background:#10161e;border:1px solid #34404c;border-radius:14px}.backdrop form>header,.preview>header{width:100%;padding:0 0 18px}.backdrop h2{margin:4px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid label{display:grid;gap:6px;color:#aeb8c2}.grid label:nth-child(6),.grid label:nth-child(7),.three{grid-column:1/-1}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}input{width:100%;border:1px solid #34404c;background:#080d13;color:white}.password-field{display:flex;gap:6px}.password-field input{min-width:0}.password-field button{white-space:nowrap}.wide{width:100%;margin-top:16px}.preview{width:min(900px,100%)}.preview img{display:block;width:100%;max-height:70vh;object-fit:contain;margin-bottom:14px;border-radius:8px;background:#05080c}.preview-error{color:#ff9ba5}@media(max-width:650px){header,.head{align-items:stretch;flex-direction:column}.summary,.grid{grid-template-columns:1fr}.grid>*{grid-column:auto!important}.list>article{grid-template-columns:42px 1fr}.actions{grid-column:1/-1}.three{grid-template-columns:1fr}}</style>
