<script>
  import { base } from '$app/paths';
  export let title = 'X';
  export let active = '';
  export let showDiscover = true;
  const groups = [
    { label: 'Workspace', links: [['dashboard','Dashboard'],['discover','Discover']] },
    { label: 'Library', links: [['repositories','Repositories'],['integrations','Integrations'],['applications','Applications']] },
    { label: 'System', links: [['queued','Queued'],['logs','Logs'],['settings','Settings']] }
  ];
  const visible = (links) => links.filter((item) => item[0] !== 'discover' || showDiscover);
  let supportOpen = false;
  let menuOpen = false;
</script>
<div class="shell">
  <aside><div class="mobile-head"><a class="brand" href={`${base}/`}><img src={`${base}/logo.png`} alt="X Platform"/><span>X Platform<small>Home Assistant</small></span></a><button class="menu-button" aria-label="Open menu" aria-expanded={menuOpen} on:click={()=>menuOpen=true}><span></span><span></span><span></span></button></div><nav class="nav-groups">{#each groups as group}{#if visible(group.links).length}<div class="nav-group"><small>{group.label}</small>{#each visible(group.links) as item}<a class:active={active === item[0]} href={`${base}/${item[0]}`}>{item[1]}</a>{/each}</div>{/if}{/each}</nav><button class="support-link desktop-help" on:click={()=>supportOpen=true}>Help & support</button></aside>
  <main><header><p>X PLATFORM</p><h1>{title}</h1></header><slot /></main>
</div>
{#if menuOpen}<div class="menu-backdrop" role="presentation" on:click={(event)=>event.currentTarget===event.target&&(menuOpen=false)}><section class="mobile-menu"><header><div><img src={`${base}/logo.png`} alt=""/><span><b>X Platform</b><small>Home Assistant</small></span></div><button aria-label="Close menu" on:click={()=>menuOpen=false}>×</button></header><nav class="nav-groups">{#each groups as group}{#if visible(group.links).length}<div class="nav-group"><small>{group.label}</small>{#each visible(group.links) as item}<a class:active={active===item[0]} href={`${base}/${item[0]}`} on:click={()=>menuOpen=false}>{item[1]}</a>{/each}</div>{/if}{/each}</nav><button class="menu-support" on:click={()=>{menuOpen=false;supportOpen=true}}>Help & support</button></section></div>{/if}
{#if supportOpen}<div class="backdrop" role="presentation" on:click={(event)=>event.currentTarget===event.target&&(supportOpen=false)}><section class="support"><button class="close" aria-label="Close" on:click={()=>supportOpen=false}>×</button><p class="eyebrow">OSAÜHING X</p><h2>How can we help?</h2><p>Questions, problems or feedback about X Platform? Include the application or integration name and its relevant log message.</p><a class="contact" href="https://extaas.com/?popover=contact_popover" target="_blank" rel="noreferrer">Open help and contact</a><div class="support-project"><h3>Support our public projects</h3><p>Your contribution helps us develop and maintain free local tools.</p><a href="https://buymeacoffee.com/extaas" target="_blank" rel="noreferrer">☕ Buy us a coffee</a></div></section></div>{/if}
<style>
  :global(*){box-sizing:border-box}:global(body){margin:0;background:#0a0d12;color:#e7e9ed;font:14px Inter,system-ui,sans-serif}:global(a){color:inherit;text-decoration:none}:global(button),:global(input),:global(select),:global(textarea){font:inherit}:global(button){cursor:pointer;border:1px solid #313844;background:#171c24;color:#e8ebef;border-radius:6px;padding:7px 11px}:global(button.primary){background:#da3;color:#191405;border-color:#da3;font-weight:700}:global(input),:global(select),:global(textarea){background:#0d1117;color:#e5e7eb;border:1px solid #303744;border-radius:6px;padding:8px;width:100%}.shell{min-height:100vh;display:grid;grid-template-columns:210px 1fr}aside{border-right:1px solid #242a33;padding:20px 12px;background:#0d1117}.brand{display:flex;align-items:center;gap:10px;padding:0 8px 24px}.brand>img{width:34px;height:34px;object-fit:contain;border-radius:8px}.brand span{display:grid;font-weight:700}.brand small{color:#7c8796;font-weight:400;font-size:10px}.nav-groups{display:grid;gap:2.5em}.nav-group{display:grid;gap:3px}.nav-group>small{color:#5f6977;font-size:9px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.nav-group a{padding:9px 10px;color:#929dab;border-radius:6px}.nav-group a.active,.nav-group a:hover{background:#242113;color:#fff;box-shadow:inset 2px 0 #da3}main{min-width:0;padding:34px clamp(18px,4vw,58px)}header{margin-bottom:25px}header p{color:#da3;font-size:10px;letter-spacing:.16em;font-weight:800;margin:0 0 5px}h1{font-size:28px;margin:0}@media(max-width:700px){.shell{display:block}aside{border-right:0;border-bottom:1px solid #242a33}.brand{padding-bottom:12px}main{padding-top:24px}}
  aside{display:flex;flex-direction:column}.support-link{position:sticky;bottom:20px;margin-top:auto;background:transparent;border:0;text-align:left;color:#929dab;padding:10px}.backdrop{position:fixed;inset:0;z-index:100;background:#000b;backdrop-filter:blur(5px);display:grid;place-items:center;padding:18px}.support{position:relative;width:min(520px,100%);background:#0e1319;border:1px solid #343b46;border-radius:14px;padding:28px;box-shadow:0 30px 100px #000}.close{position:absolute;right:14px;top:14px;border:0;border-radius:50%;font-size:20px}.eyebrow{color:#da3;font-size:10px;letter-spacing:.15em;font-weight:800;margin:18px 0 5px}.support h2{font-size:28px;margin:0 0 9px}.support>p{color:#9aa4b1;line-height:1.6}.contact,.support-project a{display:inline-flex;padding:10px 14px;border-radius:7px;background:#da3;color:#191405;font-weight:800}.support-project{margin:30px -28px -28px;padding:28px;border:0;border-top:1px solid #66551d;border-radius:0;background:linear-gradient(145deg,#211d10,#11151b)}.support-project h3{margin:0}.support-project p{color:#a9a08a}@media(max-width:700px){.support-link{position:static;margin-top:8px}}
  .mobile-head{display:contents}.menu-button{display:none}.menu-backdrop{display:none}
  @media(max-width:700px){.shell{display:block}.shell>aside{position:sticky;top:0;z-index:50;padding:0;background:#0d1117ef;backdrop-filter:blur(12px);border:0;border-bottom:1px solid #242a33}.mobile-head{height:60px;padding:10px 14px;display:flex;align-items:center;justify-content:space-between}.brand{padding:0}.brand>img{width:34px;height:34px}.brand small{display:none}.menu-button{width:38px;height:38px;display:grid;place-content:center;gap:4px;padding:0}.menu-button span{display:block;width:18px;height:2px;border-radius:2px;background:#e7e9ed}.desktop-help,.shell>aside>nav{display:none}.shell>main{padding:22px 16px 32px}.shell>main>header{margin-bottom:20px}.shell>main>header h1{font-size:24px}.menu-backdrop{position:fixed;inset:0;z-index:120;display:flex;justify-content:flex-end;background:#000a;backdrop-filter:blur(4px)}.mobile-menu{width:min(330px,88vw);min-height:100%;padding:18px;background:#0d1117;border-left:1px solid #303744;box-shadow:-25px 0 80px #000}.mobile-menu header{display:flex;align-items:center;justify-content:space-between;margin:0 0 22px}.mobile-menu header>div{display:flex;align-items:center;gap:10px}.mobile-menu header img{width:36px;height:36px;object-fit:contain}.mobile-menu header span{display:grid}.mobile-menu header small{color:#7c8796;font-size:10px}.mobile-menu header button{font-size:20px;border:0}.mobile-menu nav{display:grid;gap:4px}.mobile-menu nav a{padding:12px;color:#a8b0bb;border-radius:7px}.mobile-menu nav a.active{color:#fff;background:#242113;box-shadow:inset 3px 0 #da3}.menu-support{width:100%;margin-top:20px;text-align:left;background:transparent;color:#929dab}}
</style>
