import { cameras } from '$lib/server/store.js';
import { authenticated, authFault } from '$lib/server/onvif-auth.js';
const esc=(v)=>String(v).replace(/[&<>"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const xml=(body)=>new Response(`<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><s:Body>${body}</s:Body></s:Envelope>`,{headers:{'content-type':'application/soap+xml; charset=utf-8'}});
export async function POST({params,request,url}){const c=(await cameras()).find(x=>x.id===params.id);if(!c)return new Response('Not found',{status:404});const q=await request.text();if(!authenticated(q,c))return authFault();const base=`${url.protocol}//${url.host}/onvif/${c.id}`;
if(q.includes('GetDeviceInformation'))return xml(`<tds:GetDeviceInformationResponse><tds:Manufacturer>${esc(c.manufacturer)}</tds:Manufacturer><tds:Model>${esc(c.model)}</tds:Model><tds:FirmwareVersion>1.0</tds:FirmwareVersion><tds:SerialNumber>${esc(c.uuid)}</tds:SerialNumber><tds:HardwareId>rtsp-bridge</tds:HardwareId></tds:GetDeviceInformationResponse>`);
if(q.includes('GetSystemDateAndTime')){const d=new Date();return xml(`<tds:GetSystemDateAndTimeResponse><tds:SystemDateAndTime><tt:DateTimeType>NTP</tt:DateTimeType><tt:DaylightSavings>false</tt:DaylightSavings><tt:UTCDateTime><tt:Time><tt:Hour>${d.getUTCHours()}</tt:Hour><tt:Minute>${d.getUTCMinutes()}</tt:Minute><tt:Second>${d.getUTCSeconds()}</tt:Second></tt:Time><tt:Date><tt:Year>${d.getUTCFullYear()}</tt:Year><tt:Month>${d.getUTCMonth()+1}</tt:Month><tt:Day>${d.getUTCDate()}</tt:Day></tt:Date></tt:UTCDateTime></tds:SystemDateAndTime></tds:GetSystemDateAndTimeResponse>`)}
if(q.includes('GetServices'))return xml(`<tds:GetServicesResponse><tds:Service><tds:Namespace>http://www.onvif.org/ver10/device/wsdl</tds:Namespace><tds:XAddr>${base}/device_service</tds:XAddr></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver10/media/wsdl</tds:Namespace><tds:XAddr>${base}/media_service</tds:XAddr></tds:Service></tds:GetServicesResponse>`);
return xml(`<tds:GetCapabilitiesResponse><tds:Capabilities><tt:Device><tt:XAddr>${base}/device_service</tt:XAddr></tt:Device><tt:Media><tt:XAddr>${base}/media_service</tt:XAddr><tt:StreamingCapabilities><tt:RTPMulticast>false</tt:RTPMulticast><tt:RTP_TCP>true</tt:RTP_TCP><tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP></tt:StreamingCapabilities></tt:Media></tds:Capabilities></tds:GetCapabilitiesResponse>`)}
