<script>
  export let items=[];export let selectedMonth='';
  let year=new Date().getFullYear();
  const monthNames=['Jaan','Veebr','Märts','Apr','Mai','Juun','Juuli','Aug','Sept','Okt','Nov','Dets'];
  function daysFor(y){const start=new Date(y,0,1);const lead=(start.getDay()+6)%7;const result=Array(lead).fill(null);for(let d=new Date(y,0,1);d.getFullYear()===y;d.setDate(d.getDate()+1)){const iso=`${y}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;result.push({iso,month:d.getMonth(),count:items.filter(x=>x.date===iso).length})}return result}
  $: days=daysFor(year);$: weeks=Array.from({length:Math.ceil(days.length/7)},(_,i)=>days.slice(i*7,i*7+7));
  function choose(month){const value=`${year}-${String(month+1).padStart(2,'0')}`;selectedMonth=selectedMonth===value?'':value}
</script>
<section class="heatmap"><header><div><span class="eyebrow">Aastavaade</span><h2>Vaatamiskalender</h2></div><div class="year"><button on:click={()=>year--}>‹</button><b>{year}</b><button on:click={()=>year++}>›</button>{#if selectedMonth}<button class="clear" on:click={()=>selectedMonth=''}>Kõik kuud ×</button>{/if}</div></header><div class="months">{#each monthNames as month,i}<button class:active={selectedMonth===`${year}-${String(i+1).padStart(2,'0')}`} on:click={()=>choose(i)}>{month}</button>{/each}</div><div class="heat-scroll"><div class="heat" aria-label="Aasta kalender">{#each weeks as week}<div class="week">{#each Array(7) as _,i}{#if week[i]}<button title={`${week[i].iso}${week[i].count?` · ${week[i].count} salvestust`:''}`} class:event={week[i].count} class:selected={selectedMonth===week[i].iso.slice(0,7)} on:click={()=>choose(week[i].month)}><span>{week[i].count||''}</span></button>{:else}<i></i>{/if}{/each}</div>{/each}</div></div><footer><span><i></i> Salvestus</span><span><i class="selected"></i> Valitud kuu</span></footer></section>
<style>.heatmap{padding:22px;background:var(--panel);border:1px solid var(--line);border-radius:18px}.heatmap header{display:flex;align-items:end;justify-content:space-between;gap:16px}.heatmap h2{margin:0}.year{display:flex;align-items:center;gap:7px}.year button,.months button{border:1px solid var(--line);background:#1d1d23;color:var(--muted);border-radius:8px;padding:7px 9px;cursor:pointer}.year .clear{color:var(--gold)}.months{display:grid;grid-template-columns:repeat(12,1fr);gap:5px;margin:18px 0 10px}.months button{font-size:10px;padding:6px 2px}.months button.active{background:var(--gold);color:#171006}.heat-scroll{overflow-x:auto;padding-bottom:6px}.heat{display:flex;gap:3px;min-width:720px}.week{display:grid;grid-template-rows:repeat(7,11px);gap:3px}.week button,.week i{width:11px;height:11px;padding:0;border:0;border-radius:2px;background:#292930}.week button{cursor:pointer}.week button.event{background:#9a6a1f;box-shadow:inset 0 0 0 1px #e8b85d}.week button.selected{outline:1px solid var(--gold);outline-offset:1px}.week button span{display:none}.heatmap footer{display:flex;gap:16px;color:var(--muted);font-size:10px;margin-top:10px}.heatmap footer i{display:inline-block;width:9px;height:9px;background:#9a6a1f;border-radius:2px}.heatmap footer i.selected{background:transparent;outline:1px solid var(--gold)}@media(max-width:700px){.heatmap{padding:14px}.months{grid-template-columns:repeat(6,1fr)}.heatmap header{align-items:start}.year{flex-wrap:wrap;justify-content:end}}</style>
