import dgram from 'node:dgram';
import http from 'node:http';
import os from 'node:os';
import { cameras, settings } from './store.js';
let socket=null,proxy=null,restarting=Promise.resolve();
const ip=()=>{for(const list of Object.values(os.networkInterfaces()))for(const address of list||[])if(address.family==='IPv4'&&!address.internal)return address.address;return'127.0.0.1'};
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
const close=server=>new Promise(resolve=>server?server.close(()=>resolve()):resolve());
async function bind(){const config=await settings(),host=ip(),appPort=Number(process.env.PORT||8090);if(config.onvifPort!==appPort){proxy=http.createServer((request,response)=>{const upstream=http.request({hostname:'127.0.0.1',port:appPort,path:request.url,method:request.method,headers:{...request.headers,host:`${host}:${config.onvifPort}`}},result=>{response.writeHead(result.statusCode||502,result.headers);result.pipe(response)});upstream.on('error',error=>{response.statusCode=502;response.end(error.message)});request.pipe(upstream)});proxy.on('error',error=>console.error('[ONVIF proxy]',error.message));proxy.listen(config.onvifPort,'0.0.0.0')}
if(!config.autoDiscovery)return;socket=dgram.createSocket({type:'udp4',reuseAddr:true});socket.on('message',async(message,rinfo)=>{const body=message.toString();if(!body.includes('Probe')||!body.includes('NetworkVideoTransmitter'))return;const match=body.match(/<(?:\w+:)?MessageID>([^<]+)/);for(const camera of await cameras()){const response=`<?xml version="1.0"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl"><s:Header><a:MessageID>urn:uuid:${crypto.randomUUID()}</a:MessageID><a:RelatesTo>${esc(match?.[1]||'')}</a:RelatesTo><a:To s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/ProbeMatches</a:To><a:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/04/discovery/ProbeMatches</a:Action></s:Header><s:Body><d:ProbeMatches><d:ProbeMatch><a:EndpointReference><a:Address>urn:uuid:${camera.uuid}</a:Address></a:EndpointReference><d:Types>dn:NetworkVideoTransmitter</d:Types><d:Scopes>onvif://www.onvif.org/type/NetworkVideoTransmitter onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/name/${encodeURIComponent(camera.name)} onvif://www.onvif.org/hardware/${encodeURIComponent(camera.model)}</d:Scopes><d:XAddrs>http://${host}:${config.onvifPort}/onvif/${camera.id}/device_service</d:XAddrs><d:MetadataVersion>1</d:MetadataVersion></d:ProbeMatch></d:ProbeMatches></s:Body></s:Envelope>`;socket.send(Buffer.from(response),rinfo.port,rinfo.address)}});socket.on('error',error=>console.error('[WS-Discovery]',error.message));socket.bind(config.discoveryPort,()=>socket.addMembership('239.255.255.250'))}
export function restartDiscovery(){restarting=restarting.then(async()=>{await Promise.all([close(socket),close(proxy)]);socket=null;proxy=null;await bind()});return restarting}
export function startDiscovery(){return restartDiscovery()}
