name: Node Server
version: "2.0"
slug: node_api_server
description: Priv Github repo Node.js server addon
startup: services
boot: auto
ingress: true
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

options:
  github_token: ""
  repo: |
    "username/name.git"
  env: |
    "name=value"

schema:
  github_token: password
  repo: str
  env: str