<script>
  import { base } from '$app/paths';
  import { page } from '$app/state';
  import { onMount } from 'svelte';
  let item, message='', error='', docs={available:false,content:''}, docsOpen=false;
  const id=page.url.searchParams.get('id');
  async function api(path,options={}){const response=await fetch(`${base}/api/${path}`,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error);return data}
  async function load(){const state=await api('state');item=state.config.integrations.find(entry=>entry.id===id);docs=await api(`docs?type=integration&id=${encodeURIComponent(id)}`).catch(()=>({available:false,content:''}))}
  async function action(type){try{await api('actions',{method:'POST',body:JSON.stringify({action:type,integrationId:id})});message=type==='delete-integration'?'Delete queued.':'Download/install queued.';setTimeout(load,1200)}catch(reason){error=reason.message}}
  onMount(load);
</script>

{#if item}{#if docs.available}<button class="info-button" on:click={()=>docsOpen=true}>Info</button>{/if}<div class="facts"><article><small>Domain</small><b>{item.domain}</b></article><article><small>Installed version</small><b>{item.installedVersion||'Not installed'}</b></article><article><small>Available version</small><b>{item.version||'â€”'}</b></article><article><small>Update state</small><b>{item.installed&&item.version!==item.installedVersion?'Update available':'Current'}</b></article><article><small>Repository</small><b>{item.repository}</b></article><article><small>Path</small><b>{item.path}</b></article><article><small>Installed/updated</small><b>{item.installedAt?new Date(item.installedAt).toLocaleString():'â€”'}</b></article></div><section class="info"><h2>Managed source</h2><p>The installed source is archived under X Platform persistent storage. Removing the repository does not remove this integration.</p></section>{#if item.installed}<button class="danger" on:click={()=>confirm(`Delete ${item.name} from Home Assistant files?`)&&action('delete-integration')}>Delete</button>{:else}<button class="primary" on:click={()=>action('update-integration')}>Download</button>{/if}{/if}{#if message}<p class="ok">{message}</p>{/if}{#if error}<p class="bad">{error}</p>{/if}{#if docsOpen}<div class="docs-backdrop" on:click={(event)=>event.currentTarget===event.target&&(docsOpen=false)}><section class="docs-popover"><button on:click={()=>docsOpen=false}>← Back</button><pre>{docs.content}</pre></section></div>{/if}

<style>.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:8px}.facts article{display:grid;gap:6px;padding:14px;border:1px solid #29313b;background:#0e1319;border-radius:7px}.facts small{color:#838e9b}.facts b{color:#e7ebef;overflow-wrap:anywhere}.info{margin:18px 0;max-width:850px}.info p{color:#939eab;line-height:1.6}.info code,.ok{color:#da3}.bad,.danger{color:#f18d99}.danger{border:1px solid #633039;background:#35171b;border-radius:6px;padding:8px 12px}.info-button{margin-bottom:12px}.docs-backdrop{position:fixed;inset:0;z-index:100;background:#000b;display:grid;place-items:center;padding:18px}.docs-popover{width:min(900px,100%);max-height:90vh;display:grid;gap:10px;padding:18px;border:1px solid #303844;border-radius:10px;background:#0d1218}.docs-popover>button{justify-self:start}.docs-popover pre{margin:0;max-height:calc(90vh - 75px);overflow:auto;white-space:pre-wrap;color:#c8d0da}</style>

