name: Node Server - UI
slug: node_server_with_ui
version: "05.04.2026"
description: Priv Github repo Node.js server addon
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
homeassistant_api: true
startup: "application"
boot: auto
init: false
ingress: true
ingress_port: 3000
host_network: true
panel_icon: mdi:server
panel_title: Node Server
options:
  github_token: ""
  repo:
    - username/name.git
    - example_2/repo_2.git
  env:
    - name=value
    - example_2=value_2
schema:
  github_token: password
  repo:
    - str
  env:
    - str
