name: X Platform
version: "0.9"
slug: x_platform
description: Central Osaühing X plugin platform for Home Assistant.
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true
startup: application
boot: auto
init: false
ingress: true
ingress_port: 3000
webui: http://[HOST]:[PORT:3000]
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: X Platform Svelte web interface
host_network: true
panel_icon: mdi:puzzle
panel_title: X Platform
map:
  - homeassistant_config:rw
options:
  port: 3000
schema:
  port: port
