name: X Plugins
slug: x_installer
version: "1.5.0"
description: Installs custom components into HA automatically from /plugins folder
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true
startup: "services"
boot: auto
init: false
map:
  - homeassistant_config:rw
ingress: false
host_network: true
