name: X Plugins
slug: x_installer
version: "0.0.3"
description: Installs custom components into HA automatically from /plugins folder
arch:
  - amd64
  - aarch64
  - armv7
startup: "services"
boot: auto
init: false
ingress: false
host_network: true
options:
  path: "/config/custom_components"
schema:
  path: str