name: Node Server
version: "2.3"
slug: node_api_server
description: Priv Github repo Node.js server addon
startup: services
boot: auto
ingress: false
init: true

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
homeassistant_api: true
options:
  github_token: ""
  repo:
    - username/name.git
    - example_2/repo_2.git
  env:
    - name=value
    - example_2=value_2

schema:
  github_token: password
  repo:
    - str
  env:
    - str