name: Node API Server
version: "1.2"
slug: node_api_server
description: Node.js server addon
startup: services
boot: auto
ingress: true

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

options:
  repo: "username/name.git"
  github_token: ""

schema:
  repo: str
  github_token: password
  