name: NodeJS Plugin Installer
slug: nodejs_plugin_installer
version: "1.0.0"
description: Installs custom components into HA automatically from /plugins folder
arch:
  - amd64
  - aarch64
  - armv7
startup: "application"
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:home-assistant
panel_title: Plugin Installer
host_network: true
options: {}
schema: {}